//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFO.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inseminacionporcina
    {
        public int idinseminacion { get; set; }
        public string cedulaproductor { get; set; }
        public string nombreproductor { get; set; }
        public Nullable<int> idmunicipio3 { get; set; }
        public Nullable<int> idcomunidad2 { get; set; }
        public string coordenadaX { get; set; }
        public string coordenadaY { get; set; }
        public string sexo { get; set; }
        public string numerotelfono { get; set; }
        public Nullable<System.DateTime> fechainseminacion { get; set; }
        public string nombrecerdo { get; set; }
        public Nullable<int> idrazascerdos1 { get; set; }
        public string presentocelo { get; set; }
        public Nullable<System.DateTime> fecharealdepartop { get; set; }
        public Nullable<int> machos { get; set; }
        public Nullable<int> hembras { get; set; }
        public Nullable<int> totalnacidos { get; set; }
    
        public virtual comunidad comunidad { get; set; }
        public virtual municipios municipios { get; set; }
        public virtual razascerdos razascerdos { get; set; }
    }
}
