//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFO.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metas
    {
        public int idmetas { get; set; }
        public Nullable<int> idestrategia2 { get; set; }
        public Nullable<int> idtiposactividad2 { get; set; }
        public Nullable<int> idinstitucion2 { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
