//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFO.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguimiento
    {
        public int idsegimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idmunicipio1 { get; set; }
        public Nullable<int> idcomunidad1 { get; set; }
        public Nullable<int> idinstitucion1 { get; set; }
        public Nullable<int> idestrategia1 { get; set; }
        public Nullable<int> idtiposactividad1 { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> varones { get; set; }
        public Nullable<int> mujeres { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual comunidad comunidad { get; set; }
        public virtual estrategia estrategia { get; set; }
        public virtual institucion institucion { get; set; }
        public virtual municipios municipios { get; set; }
        public virtual tipos_de_actividades tipos_de_actividades { get; set; }
    }
}
