//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFO.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public string password { get; set; }
        public string primernombre { get; set; }
        public string ultimonombre { get; set; }
        public string posicion { get; set; }
        public string Email { get; set; }
    }
}
